api_platform:
    title: UniService API
    version: 0.0.1
#    eager_loading:
#        max_joins: 100
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
