services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Security\PermissionProviderInterface:
      tags: [ 'app.permission_provider' ]

  StageBundle\:
    resource: '../../'
    exclude:
      - '../../Entity/'
      - '../../StageBundle.php'
