services:
  _defaults:
    autowire: true
    autoconfigure: true

  QuestionnaireBundle\:
    resource: '../../'
    exclude:
      - '../../Entity/'
      - '../../DependencyInjection/'
      - '../../QuestionnaireBundle.php'

  QuestionnaireBundle\Domain\Questionnaire\Repeat\RepeatItemsProviderRegistry:
    arguments:
      $providers: !tagged_iterator app.repeat_items_provider

#  QuestionnaireBundle\Infrastructure\Questionnaire\Repeat\MatiereRepeatItemsProvider:
#    tags: [ 'app.repeat_items_provider' ]
