services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Domain\Dashboard\WidgetProviderInterface:
      tags: [ 'app.dashboard.widget_provider' ]
    App\Domain\Dashboard\WidgetDataProviderInterface:
      tags: [ 'app.dashboard.widget_data_provider' ]
    App\Security\PermissionProviderInterface:
      tags: [ 'app.permission_provider' ]

  QuestionnaireBundle\:
    resource: '../../'
    exclude:
      - '../../Entity/'
      - '../../DependencyInjection/'
      - '../../QuestionnaireBundle.php'

  QuestionnaireBundle\Domain\Questionnaire\Repeat\RepeatItemsProviderRegistry:
    arguments:
      $providers: !tagged_iterator app.repeat_items_provider

#  QuestionnaireBundle\Infrastructure\Questionnaire\Repeat\MatiereRepeatItemsProvider:
#    tags: [ 'app.repeat_items_provider' ]
