services:
  web:
    image: mmi3docker/symfony-2024
    container_name : uniservice-web
    hostname: uniservice-web
    restart: always
    platform: linux/amd64
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db
    volumes:
      - ./back:/var/www/uniservice
      - ./apache.conf:/etc/apache2/sites-enabled/000-default.conf

  db:
    image: mariadb:10.8
    container_name: uniservice-db
    hostname: uniservice-db
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-volume:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: uniservice-adminsql
    hostname: uniservice-adminsql
    restart: always
    platform: linux/amd64
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  maildev:
    image: maildev/maildev
    container_name: uniservice-mail
    hostname: uniservice-mail
    command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
    restart: always

    ports:
      - ${MAILDEV_PORT}:1080

volumes:
  db-volume:
