<?php

namespace StageBundle\Enum;

enum EtatStageEnum: string
{
    case AUTORISE = 'ETAT_STAGE_AUTORISE';
    case DEPOSE = 'ETAT_STAGE_DEPOSE';
    case VALIDE = 'ETAT_STAGE_VALIDE';
    case REFUS = 'ETAT_STAGE_REFUS';
    case INCOMPLET = 'ETAT_STAGE_INCOMPLET';
    case CONVENTION_IMPRIMEE = 'ETAT_STAGE_CONVENTION_IMPRIMEE';
    case CONVENTION_ENVOYEE = 'ETAT_STAGE_CONVENTION_ENVOYEE';
    case CONVENTION_RECUE = 'ETAT_STAGE_CONVENTION_RECUE';
}
