services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Domain\Dashboard\WidgetProviderInterface:
      tags: [ 'app.dashboard.widget_provider' ]
    App\Domain\Dashboard\WidgetDataProviderInterface:
      tags: [ 'app.dashboard.widget_data_provider' ]

  UnifolioBundle\:
    resource: '../../'
    exclude:
      - '../../Entity/'
      - '../../DependencyInjection/'
      - '../../UnifolioBundle.php'
