# docker/nginx/default.conf
server {
    listen 80;
    server_name _;
    root /var/www/html/back/public;
    index index.php;

    # Logs
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    # Sécurité - headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Taille max upload
    client_max_body_size 50M;

   # Assets statiques avec cache long
       location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|map)$ {
           expires 1y;
           add_header Cache-Control "public, immutable";
           try_files $uri =404;
       }

       # SPAs des bundles
       location /auth {
           alias /var/www/html/back/public/build/auth-bundle;
           try_files $uri $uri/ /build/auth-bundle/index.html;
           index index.html;
       }

       location /intranet {
           alias /var/www/html/back/public/build/intranet-bundle;
           try_files $uri $uri/ /build/intranet-bundle/index.html;
           index index.html;
       }

       location /edt {
           alias /var/www/html/back/public/build/edt-bundle;
           try_files $uri $uri/ /build/edt-bundle/index.html;
           index index.html;
       }

       location /unifolio {
           alias /var/www/html/back/public/build/unifolio-bundle;
           try_files $uri $uri/ /build/unifolio-bundle/index.html;
           index index.html;
       }

    # Symfony front controller
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # PHP-FPM
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT   $realpath_root;

        # Timeouts
        fastcgi_read_timeout 60;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;

        internal;
    }

    # Bloquer l'accès aux autres .php
    location ~ \.php$ {
        return 404;
    }

    # Bloquer l'accès aux fichiers sensibles
    location ~ /\.(ht|git|env) {
        deny all;
        return 404;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt  {
        log_not_found off;
        access_log off;
    }
}
