<script setup>
</script>

<template>
    <div class="card">
        <div class="font-semibold text-xl mb-4">Empty Page</div>
        <p>Use this page to start from scratch and place your custom content.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam laoreet, nisi eu tempor lobortis, tortor purus tempor est, in efficitur massa massa vitae odio. Vivamus mattis dignissim neque eget rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed ac libero elit. Fusce vel suscipit mi. Suspendisse lobortis venenatis nisl, sodales consequat dui elementum ac. Phasellus efficitur lorem in porttitor imperdiet.

            Donec at hendrerit libero, ut tincidunt mi. Nullam vel justo purus. Fusce elit neque, ornare at magna quis, ullamcorper malesuada lectus. Duis imperdiet ante ligula, sit amet molestie lectus blandit ut. Pellentesque condimentum elementum mi in placerat. Cras nunc nulla, interdum ut diam quis, fringilla imperdiet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vitae erat facilisis, dapibus eros in, consequat nibh.

            Pellentesque vestibulum pulvinar congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut tellus metus, condimentum a magna eget, suscipit malesuada leo. Cras placerat, leo ac cursus feugiat, velit ex condimentum ex, sed lobortis velit nunc quis justo. Etiam euismod est et tortor venenatis commodo. Sed ante orci, efficitur sed risus vel, ornare condimentum massa. Aliquam leo justo, hendrerit at mi vitae, imperdiet convallis elit. In fermentum nec augue in fermentum. Quisque eget ornare dolor. Cras eget ornare ipsum, non accumsan orci.

            Cras ut metus aliquet, consectetur mauris porta, bibendum felis. Ut viverra metus eu mauris cursus, ut auctor neque aliquet. Etiam convallis, diam in lobortis sagittis, metus ex auctor justo, non interdum orci nunc nec ligula. Etiam ut sem hendrerit, varius velit sagittis, interdum lorem. Integer rutrum tellus at nisi scelerisque euismod. Integer ligula lectus, mollis sed semper ut, tempus non nibh. Donec faucibus porttitor ipsum vitae finibus.

            Nam facilisis malesuada egestas. Pellentesque maximus dapibus nisl at venenatis. Suspendisse iaculis, erat ut pulvinar suscipit, nisi odio laoreet dolor, eu convallis ipsum lacus nec velit. Cras consequat pellentesque lacinia. Nam mattis tortor dui, nec pretium mauris placerat vel. Phasellus ornare semper lectus a tempus. Vestibulum lacinia leo id felis cursus, eu vestibulum dui semper. Mauris venenatis justo in purus mollis, eget vulputate felis luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas in urna quis lacus feugiat sagittis.

            Curabitur pellentesque dictum nulla et efficitur. Etiam hendrerit eros sed nulla ullamcorper, vitae mattis orci convallis. Quisque elit justo, egestas quis vestibulum a, luctus ut nibh. Donec a tellus suscipit, aliquam enim eu, cursus nunc. Maecenas cursus lacinia sapien. Maecenas finibus velit turpis, non accumsan dui fringilla vel. Nulla egestas augue lorem, in sodales diam congue eu.

            Nullam convallis sem vitae euismod euismod. Ut accumsan purus sit amet commodo luctus. Quisque sit amet semper tortor. In est dolor, bibendum feugiat cursus in, bibendum ut risus. Nam ut ligula erat. Integer ex felis, lacinia a mi at, dictum cursus elit. Aenean non imperdiet lacus, consectetur finibus erat. Fusce mollis, ex non vestibulum viverra, magna velit ultricies lacus, quis dapibus tortor purus at ex. Sed bibendum neque ipsum, in consectetur quam fringilla eget. Sed in accumsan tortor, sit amet pharetra ex. Phasellus ante dolor, vestibulum nec felis nec, porttitor maximus risus. Etiam eget hendrerit magna. Donec ultricies venenatis erat, sit amet tempus lorem pulvinar nec. Nam dolor neque, maximus sed aliquam et, auctor ut mauris.

            Curabitur viverra in dolor eget luctus. Morbi rhoncus felis non risus iaculis, sed mollis odio auctor. Suspendisse ut nibh eget ipsum facilisis facilisis. In suscipit hendrerit nibh, in iaculis dolor ornare id. Suspendisse venenatis sit amet arcu eget bibendum. Quisque ac ipsum hendrerit, ullamcorper leo at, porttitor magna. Cras vel mattis tortor, at sagittis mauris. Aliquam sed mattis augue, vel efficitur ipsum. Ut semper justo at ligula vulputate venenatis.

            Aenean eu scelerisque orci, vitae vestibulum leo. Sed convallis venenatis malesuada. Duis eget urna at nisi porttitor commodo in et felis. Morbi vel justo tincidunt, imperdiet turpis in, tincidunt elit. Phasellus pulvinar arcu ac justo volutpat fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla facilisi. Aenean vitae orci ac diam maximus tincidunt. Sed faucibus erat nec dolor sodales, id imperdiet turpis ornare. Integer ante velit, vulputate id mattis efficitur, aliquam quis justo. Donec maximus scelerisque vestibulum. Maecenas lacinia orci sagittis lorem luctus, suscipit sollicitudin risus semper. Etiam mattis, sem a molestie euismod, orci massa finibus velit, a convallis nulla nisi id mauris. Nullam auctor pellentesque rutrum. Phasellus condimentum lacus condimentum turpis malesuada, quis iaculis ex iaculis.

            Phasellus sollicitudin, mi ac suscipit pharetra, metus lorem dictum nulla, et ultrices mauris turpis pretium mauris. Cras quis lacus egestas, suscipit risus ac, volutpat mauris. Mauris ultrices orci eu felis cursus, vitae viverra augue vestibulum. Nulla tempor magna ac dolor pulvinar molestie. Mauris venenatis, mauris sed molestie viverra, ex quam vestibulum libero, a consequat metus purus vitae mauris. Nullam eget vestibulum nisi. Proin faucibus, massa sed rhoncus imperdiet, elit elit efficitur arcu, ut bibendum sem diam consectetur mauris. Nulla ligula magna, porta eget fermentum eget, sodales a lectus. Nulla dapibus varius metus vitae vehicula. Nulla ac mi rhoncus, suscipit elit id, dictum risus. Nulla at est eget leo pretium imperdiet eget varius justo. Mauris in augue odio. Maecenas lacinia commodo dui nec varius. Maecenas rutrum diam magna, in malesuada diam ornare ac. Donec gravida aliquet nulla, eget venenatis tortor placerat vel. Suspendisse nec cursus mi.

            Maecenas vestibulum pharetra arcu, et feugiat mi sodales vestibulum. Quisque felis nunc, efficitur nec vestibulum ac, varius vitae tellus. Etiam porttitor auctor ornare. In at purus eu tellus aliquam consequat eu ac nisl. Quisque malesuada, risus et posuere scelerisque, leo justo efficitur est, quis lacinia turpis massa at erat. Fusce tempus, orci id rutrum molestie, libero mauris facilisis quam, eget lobortis dui nulla quis erat. Sed facilisis vulputate condimentum. Nunc ut aliquam nibh, eu efficitur velit. Suspendisse leo metus, ornare nec dolor a, malesuada sodales libero. Curabitur congue, nisl quis tempor ornare, eros est volutpat urna, in malesuada ante tellus ut ex. Donec diam nisl, porta a leo in, viverra dignissim lectus. Curabitur eleifend sit amet mi et porta. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sagittis interdum nisl lacinia tincidunt. Etiam vel hendrerit felis.

            Proin bibendum magna in elit tristique porttitor. Integer ullamcorper porta tristique. Donec nec posuere magna. Sed et ornare urna. Quisque malesuada magna a ipsum blandit, quis blandit dui sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet pellentesque ante, et mollis est. Etiam interdum facilisis neque, vitae condimentum eros sodales at.

            Donec sit amet varius metus. Integer malesuada ultricies urna, ac vehicula ligula pellentesque vel. Mauris tempus convallis felis et interdum. Sed tristique dui sed eros gravida, quis auctor enim consectetur. Sed imperdiet at mi a suscipit. Vestibulum ac blandit enim, id auctor ex. Proin a leo ac felis accumsan porttitor. Pellentesque sed porttitor dui. Fusce non tellus a neque hendrerit feugiat nec non urna.

            Maecenas a porttitor turpis. Praesent imperdiet dapibus mauris, vel tincidunt lacus rhoncus sit amet. Cras sit amet varius lorem. Suspendisse id finibus est. Quisque neque lectus, semper at commodo ac, pellentesque et ex. Vivamus dictum suscipit eros vel finibus. Phasellus fringilla, odio non convallis pretium, enim ipsum gravida elit, vel imperdiet velit nisi scelerisque sem.

            Aliquam lobortis ultricies eleifend. Praesent efficitur nulla ut mauris vestibulum, tincidunt tincidunt eros imperdiet. Mauris eu consectetur ligula. Pellentesque rutrum auctor ante, eu pellentesque velit bibendum et. Nulla id eros hendrerit, lobortis sapien ac, commodo arcu. Integer pretium ex vehicula tortor varius, non dictum lorem ullamcorper. Curabitur finibus consequat dapibus. Pellentesque vitae mollis libero.

            Phasellus ac dui id dolor mattis gravida. Vivamus a erat justo. Fusce gravida diam quis erat elementum posuere. Aliquam eu egestas leo, a placerat erat. Donec non rutrum diam, ac pellentesque neque. Praesent eu tortor lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent elementum sed lorem vitae finibus. Fusce efficitur augue eu feugiat consectetur. Vivamus a metus hendrerit, sodales nibh et, dapibus libero. Cras at rutrum est. Curabitur tempor blandit tristique.

            Maecenas ullamcorper facilisis urna eu sodales. Aliquam tincidunt sem neque, quis fermentum eros rutrum et. Nunc nisl tellus, commodo nec venenatis ut, rutrum id dui. Vestibulum faucibus a nulla eget blandit. In hac habitasse platea dictumst. Etiam pharetra blandit maximus. Donec non est lacus. Phasellus accumsan ipsum eu facilisis imperdiet. Etiam cursus leo diam, ac ultrices dolor vehicula ac. Mauris euismod ut dui eget euismod.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam laoreet, nisi eu tempor lobortis, tortor purus tempor est, in efficitur massa massa vitae odio. Vivamus mattis dignissim neque eget rhoncus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed ac libero elit. Fusce vel suscipit mi. Suspendisse lobortis venenatis nisl, sodales consequat dui elementum ac. Phasellus efficitur lorem in porttitor imperdiet.

            Donec at hendrerit libero, ut tincidunt mi. Nullam vel justo purus. Fusce elit neque, ornare at magna quis, ullamcorper malesuada lectus. Duis imperdiet ante ligula, sit amet molestie lectus blandit ut. Pellentesque condimentum elementum mi in placerat. Cras nunc nulla, interdum ut diam quis, fringilla imperdiet massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vitae erat facilisis, dapibus eros in, consequat nibh.

            Pellentesque vestibulum pulvinar congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut tellus metus, condimentum a magna eget, suscipit malesuada leo. Cras placerat, leo ac cursus feugiat, velit ex condimentum ex, sed lobortis velit nunc quis justo. Etiam euismod est et tortor venenatis commodo. Sed ante orci, efficitur sed risus vel, ornare condimentum massa. Aliquam leo justo, hendrerit at mi vitae, imperdiet convallis elit. In fermentum nec augue in fermentum. Quisque eget ornare dolor. Cras eget ornare ipsum, non accumsan orci.

            Cras ut metus aliquet, consectetur mauris porta, bibendum felis. Ut viverra metus eu mauris cursus, ut auctor neque aliquet. Etiam convallis, diam in lobortis sagittis, metus ex auctor justo, non interdum orci nunc nec ligula. Etiam ut sem hendrerit, varius velit sagittis, interdum lorem. Integer rutrum tellus at nisi scelerisque euismod. Integer ligula lectus, mollis sed semper ut, tempus non nibh. Donec faucibus porttitor ipsum vitae finibus.

            Nam facilisis malesuada egestas. Pellentesque maximus dapibus nisl at venenatis. Suspendisse iaculis, erat ut pulvinar suscipit, nisi odio laoreet dolor, eu convallis ipsum lacus nec velit. Cras consequat pellentesque lacinia. Nam mattis tortor dui, nec pretium mauris placerat vel. Phasellus ornare semper lectus a tempus. Vestibulum lacinia leo id felis cursus, eu vestibulum dui semper. Mauris venenatis justo in purus mollis, eget vulputate felis luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas in urna quis lacus feugiat sagittis.

            Curabitur pellentesque dictum nulla et efficitur. Etiam hendrerit eros sed nulla ullamcorper, vitae mattis orci convallis. Quisque elit justo, egestas quis vestibulum a, luctus ut nibh. Donec a tellus suscipit, aliquam enim eu, cursus nunc. Maecenas cursus lacinia sapien. Maecenas finibus velit turpis, non accumsan dui fringilla vel. Nulla egestas augue lorem, in sodales diam congue eu.

            Nullam convallis sem vitae euismod euismod. Ut accumsan purus sit amet commodo luctus. Quisque sit amet semper tortor. In est dolor, bibendum feugiat cursus in, bibendum ut risus. Nam ut ligula erat. Integer ex felis, lacinia a mi at, dictum cursus elit. Aenean non imperdiet lacus, consectetur finibus erat. Fusce mollis, ex non vestibulum viverra, magna velit ultricies lacus, quis dapibus tortor purus at ex. Sed bibendum neque ipsum, in consectetur quam fringilla eget. Sed in accumsan tortor, sit amet pharetra ex. Phasellus ante dolor, vestibulum nec felis nec, porttitor maximus risus. Etiam eget hendrerit magna. Donec ultricies venenatis erat, sit amet tempus lorem pulvinar nec. Nam dolor neque, maximus sed aliquam et, auctor ut mauris.

            Curabitur viverra in dolor eget luctus. Morbi rhoncus felis non risus iaculis, sed mollis odio auctor. Suspendisse ut nibh eget ipsum facilisis facilisis. In suscipit hendrerit nibh, in iaculis dolor ornare id. Suspendisse venenatis sit amet arcu eget bibendum. Quisque ac ipsum hendrerit, ullamcorper leo at, porttitor magna. Cras vel mattis tortor, at sagittis mauris. Aliquam sed mattis augue, vel efficitur ipsum. Ut semper justo at ligula vulputate venenatis.

            Aenean eu scelerisque orci, vitae vestibulum leo. Sed convallis venenatis malesuada. Duis eget urna at nisi porttitor commodo in et felis. Morbi vel justo tincidunt, imperdiet turpis in, tincidunt elit. Phasellus pulvinar arcu ac justo volutpat fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla facilisi. Aenean vitae orci ac diam maximus tincidunt. Sed faucibus erat nec dolor sodales, id imperdiet turpis ornare. Integer ante velit, vulputate id mattis efficitur, aliquam quis justo. Donec maximus scelerisque vestibulum. Maecenas lacinia orci sagittis lorem luctus, suscipit sollicitudin risus semper. Etiam mattis, sem a molestie euismod, orci massa finibus velit, a convallis nulla nisi id mauris. Nullam auctor pellentesque rutrum. Phasellus condimentum lacus condimentum turpis malesuada, quis iaculis ex iaculis.

            Phasellus sollicitudin, mi ac suscipit pharetra, metus lorem dictum nulla, et ultrices mauris turpis pretium mauris. Cras quis lacus egestas, suscipit risus ac, volutpat mauris. Mauris ultrices orci eu felis cursus, vitae viverra augue vestibulum. Nulla tempor magna ac dolor pulvinar molestie. Mauris venenatis, mauris sed molestie viverra, ex quam vestibulum libero, a consequat metus purus vitae mauris. Nullam eget vestibulum nisi. Proin faucibus, massa sed rhoncus imperdiet, elit elit efficitur arcu, ut bibendum sem diam consectetur mauris. Nulla ligula magna, porta eget fermentum eget, sodales a lectus. Nulla dapibus varius metus vitae vehicula. Nulla ac mi rhoncus, suscipit elit id, dictum risus. Nulla at est eget leo pretium imperdiet eget varius justo. Mauris in augue odio. Maecenas lacinia commodo dui nec varius. Maecenas rutrum diam magna, in malesuada diam ornare ac. Donec gravida aliquet nulla, eget venenatis tortor placerat vel. Suspendisse nec cursus mi.

            Maecenas vestibulum pharetra arcu, et feugiat mi sodales vestibulum. Quisque felis nunc, efficitur nec vestibulum ac, varius vitae tellus. Etiam porttitor auctor ornare. In at purus eu tellus aliquam consequat eu ac nisl. Quisque malesuada, risus et posuere scelerisque, leo justo efficitur est, quis lacinia turpis massa at erat. Fusce tempus, orci id rutrum molestie, libero mauris facilisis quam, eget lobortis dui nulla quis erat. Sed facilisis vulputate condimentum. Nunc ut aliquam nibh, eu efficitur velit. Suspendisse leo metus, ornare nec dolor a, malesuada sodales libero. Curabitur congue, nisl quis tempor ornare, eros est volutpat urna, in malesuada ante tellus ut ex. Donec diam nisl, porta a leo in, viverra dignissim lectus. Curabitur eleifend sit amet mi et porta. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sagittis interdum nisl lacinia tincidunt. Etiam vel hendrerit felis.

            Proin bibendum magna in elit tristique porttitor. Integer ullamcorper porta tristique. Donec nec posuere magna. Sed et ornare urna. Quisque malesuada magna a ipsum blandit, quis blandit dui sodales. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sit amet pellentesque ante, et mollis est. Etiam interdum facilisis neque, vitae condimentum eros sodales at.

            Donec sit amet varius metus. Integer malesuada ultricies urna, ac vehicula ligula pellentesque vel. Mauris tempus convallis felis et interdum. Sed tristique dui sed eros gravida, quis auctor enim consectetur. Sed imperdiet at mi a suscipit. Vestibulum ac blandit enim, id auctor ex. Proin a leo ac felis accumsan porttitor. Pellentesque sed porttitor dui. Fusce non tellus a neque hendrerit feugiat nec non urna.

            Maecenas a porttitor turpis. Praesent imperdiet dapibus mauris, vel tincidunt lacus rhoncus sit amet. Cras sit amet varius lorem. Suspendisse id finibus est. Quisque neque lectus, semper at commodo ac, pellentesque et ex. Vivamus dictum suscipit eros vel finibus. Phasellus fringilla, odio non convallis pretium, enim ipsum gravida elit, vel imperdiet velit nisi scelerisque sem.

            Aliquam lobortis ultricies eleifend. Praesent efficitur nulla ut mauris vestibulum, tincidunt tincidunt eros imperdiet. Mauris eu consectetur ligula. Pellentesque rutrum auctor ante, eu pellentesque velit bibendum et. Nulla id eros hendrerit, lobortis sapien ac, commodo arcu. Integer pretium ex vehicula tortor varius, non dictum lorem ullamcorper. Curabitur finibus consequat dapibus. Pellentesque vitae mollis libero.

            Phasellus ac dui id dolor mattis gravida. Vivamus a erat justo. Fusce gravida diam quis erat elementum posuere. Aliquam eu egestas leo, a placerat erat. Donec non rutrum diam, ac pellentesque neque. Praesent eu tortor lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent elementum sed lorem vitae finibus. Fusce efficitur augue eu feugiat consectetur. Vivamus a metus hendrerit, sodales nibh et, dapibus libero. Cras at rutrum est. Curabitur tempor blandit tristique.

            Maecenas ullamcorper facilisis urna eu sodales. Aliquam tincidunt sem neque, quis fermentum eros rutrum et. Nunc nisl tellus, commodo nec venenatis ut, rutrum id dui. Vestibulum faucibus a nulla eget blandit. In hac habitasse platea dictumst. Etiam pharetra blandit maximus. Donec non est lacus. Phasellus accumsan ipsum eu facilisis imperdiet. Etiam cursus leo diam, ac ultrices dolor vehicula ac. Mauris euismod ut dui eget euismod</p>
    </div>
</template>
