services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Security\PermissionProviderInterface:
      tags: [ 'app.permission_provider' ]
    App\Services\Email\AbstractEmailDefinition:
      tags: [ 'app.email_definition' ]

  HelpdeskBundle\:
    resource: '../../'
    exclude:
      - '../../Entity/'
      - '../../HelpdeskBundle.php'
