export * from './structure_services/departementService';
export * from './structure_services/diplomeService';
export * from './structure_services/anneeService';
export * from './structure_services/semestreService';
export * from './structure_services/anneeUnivService';
export * from './user_services/etudiantService';
export * from './user_services/personnelService';
export * from './user_services/userService';
export * from './ext_data_services/siteIutService';
