name: CI-Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install dependencies
        working-directory: ./back
        run: composer install --no-progress --no-interaction

      - name: Set up database
        working-directory: ./back
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:schema:update --force --env=test
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1' # Version compatible avec pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install front dependencies
        working-directory: ./front
        run: pnpm install

      - name: Run Cypress tests
        working-directory: ./front
        run: npx cypress run
