name: CI-Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cypress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Setup Composer
        run: composer self-update

      - name: Setup Symfony CLI
        run: curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash && sudo apt install symfony-cli

      - name: Install back-end dependencies
        working-directory: ./back
        run: composer install --no-progress --no-interaction

      - name: Install TLS
        working-directory: ./back
        run: symfony server:ca:install

      - name: Set up .env.test file
        working-directory: ./back
        run: cp .env .env.test

      - name: Run database migrations and load fixtures
        working-directory: ./back
        env:
          DATABASE_URL: 'mysql://root:root@127.0.0.1:3306/cypress_test'
        run: |
          php bin/console doctrine:database:create --if-not-exists --no-interaction  --env=test
          php bin/console doctrine:schema:update --force --no-interaction  --env=test
          php bin/console doctrine:fixtures:load --no-interaction  --env=test


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1' # Version compatible avec pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install front-end dependencies
        working-directory: ./front
        run: pnpm install --no-frozen-lockfile

      - name: run servers
        run: make start-all

      - name: Wait for front-end server
        run: |
          until curl -s http://localhost:3000 > /dev/null; do
            echo "Waiting for front-end server..."
            sleep 1
          done

      - name: Wait for Symfony server
        run: |
          until curl -s https://127.0.0.1:8000 > /dev/null; do
            echo "Waiting for Symfony server..."
            sleep 1
          done
          
      - name: Wait for Symfony server
        run: |
          until curl -s https://127.0.0.1:8000 > /dev/null; do
            echo "Waiting for Symfony server..."
            sleep 1
          done

      - name: Run Cypress tests
        working-directory: ./front
        run: npx cypress run

      - name: Stop Symfony server
        run: symfony server:stop
