name: CI-Front

on:
  push:
    branches: [main]
    paths: 
    - 'front/**'
  pull_request:
    branches: [main]
    paths: 
    - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1' # Version compatible avec pnpm

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install front dependencies
      working-directory: ./front
      run: pnpm install --no-frozen-lockfile

    - name: Run frontend tests
      working-directory: ./front
      run: npm run test
