name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.1' # Version minimum compatible avec pnpm

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install front dependencies
      working-directory: ./front
      run: pnpm install

    - name: Run frontend tests
      working-directory: ./front
      run: pnpm run test
